const allowedHosts=new Set(['zillow.com','www.zillow.com','realtor.com','www.realtor.com','redfin.com','www.redfin.com','lennar.com','www.lennar.com','drhorton.com','www.drhorton.com','pulte.com','www.pulte.com','kbhome.com','www.kbhome.com','coventryhomes.com','www.coventryhomes.com','dreamfindershomes.com','www.dreamfindershomes.com','perryhomes.com','www.perryhomes.com','meritagehomes.com','www.meritagehomes.com']);
const security={'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'",'Cache-Control':'no-store'};
export function validateURL(value){let u;try{u=new URL(value);}catch{throw Error('Enter a valid listing URL.');}if(u.protocol!=='https:'||u.username||u.password||u.port||!allowedHosts.has(u.hostname))throw Error('Direct import supports Zillow, Realtor.com, Redfin, Lennar, D.R. Horton, Pulte, KB Home, Coventry, Dream Finders, Perry and Meritage. For other sites, paste the listing text.');u.hash='';return u;}
async function limitedText(response,max){const declared=Number(response.headers.get('content-length'));if(declared>max)throw Error('The listing page is too large to import.');if(!response.body)return '';const reader=response.body.getReader(),chunks=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>max)throw Error('The listing page is too large to import.');chunks.push(value);}}finally{await reader.cancel().catch(()=>{});}const bytes=new Uint8Array(size);let at=0;for(const c of chunks){bytes.set(c,at);at+=c.byteLength;}return new TextDecoder().decode(bytes);}
export function robotsAllows(text,path){const groups=[];let group=null,hasRules=false;for(let line of text.split(/\r?\n/)){line=line.split('#')[0].trim();const m=line.match(/^([^:]+):\s*(.*)$/);if(!m)continue;const key=m[1].trim().toLowerCase(),value=m[2].trim();if(key==='user-agent'){if(!group||hasRules){group={agents:[],rules:[]};groups.push(group);hasRules=false;}group.agents.push(value.toLowerCase());}else if(group&&['allow','disallow'].includes(key)){group.rules.push({allow:key==='allow',path:value});hasRules=true;}}
const exact=groups.filter(g=>g.agents.some(a=>a!=='*'&&'homecomparebot'.includes(a)));const relevant=exact.length?exact:groups.filter(g=>g.agents.includes('*'));let best=null;for(const g of relevant)for(const rule of g.rules){if(!rule.path)continue;if(rule.path.length>2000||(rule.path.match(/\*/g)||[]).length>10)return false;const end=rule.path.endsWith('$'),raw=end?rule.path.slice(0,-1):rule.path;const pattern='^'+raw.split('*').map(p=>p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('.*')+(end?'$':'');if(new RegExp(pattern).test(path)&&(!best||rule.path.length>best.path.length||rule.path.length===best.path.length&&rule.allow))best=rule;}return !best||best.allow;}
export async function importURL(value,fetcher=fetch){let u=validateURL(value);const signal=AbortSignal.timeout(12000),headers={'User-Agent':'HomeCompareBot/1.0','Accept':'text/html,application/xhtml+xml'};
for(let redirects=0;redirects<4;redirects++){const robots=await fetcher(u.origin+'/robots.txt',{headers,redirect:'manual',signal});if(robots.status!==404){if(!robots.ok)throw Error('The site’s automated-access rules could not be verified.');if(/text\/html/i.test(robots.headers.get('content-type')||''))throw Error('The site’s automated-access rules could not be verified.');const rules=await limitedText(robots,65536);if(!robotsAllows(rules,u.pathname+u.search))throw Error('This site does not permit automated access to that listing.');}
const r=await fetcher(u.href,{headers,redirect:'manual',signal});if(r.status>=300&&r.status<400){const dest=r.headers.get('location');if(!dest)throw Error('The listing redirected without a destination.');u=validateURL(new URL(dest,u).href);continue;}if(!r.ok)throw Error('The listing site blocked access or returned an unavailable page.');if(!/(?:text\/html|application\/xhtml\+xml)/i.test(r.headers.get('content-type')||''))throw Error('This URL did not return a listing web page.');const html=await limitedText(r,2000000);if(/<title[^>]*>\s*(?:Just a moment|Access denied|Robot or human|Security check)/i.test(html)||/verify you are human|press & hold to confirm/i.test(html))throw Error('The listing requires a browser verification step.');const result=globalThis.HomeListingImport.extractListing(html);return {...result,sourceUrl:u.href};}
throw Error('Too many listing redirects.');}
const rateWindows=new Map();
export async function handle(request,assets,fetcher=fetch){const url=new URL(request.url);if(url.pathname==='/api/listing'){if(request.method!=='POST')return json({error:'Use POST.'},405);if(!request.headers.get('content-type')?.startsWith('application/json'))return json({error:'Expected JSON.'},415);const origin=request.headers.get('origin');if(origin&&origin!==url.origin)return json({error:'Cross-origin imports are not allowed.'},403);const key=request.headers.get('cf-connecting-ip')||'local';const now=Date.now();let bucket=rateWindows.get(key);if(!bucket||now-bucket.start>60000){bucket={start:now,count:0};rateWindows.set(key,bucket);}if(rateWindows.size>1000){for(const [k,b]of rateWindows)if(now-b.start>60000)rateWindows.delete(k);if(rateWindows.size>1000)return json({error:'Importer is busy. Try again shortly.'},429);}if(++bucket.count>10)return json({error:'Please wait a minute before importing more listings.'},429);try{const body=await limitedText(request,4096),input=JSON.parse(body);if(typeof input.url!=='string'||input.url.length>2000)return json({error:'Enter a listing URL under 2,000 characters.'},400);return json(await importURL(input.url,fetcher),200);}catch(error){return json({error:error.name==='TimeoutError'?'The listing timed out.':error instanceof SyntaxError?'Invalid request.':error.message},422);}}
if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405,headers:security});const file=url.pathname==='/'?'/index.html':url.pathname,asset=assets[file];if(!asset)return new Response('Not found',{status:404,headers:security});const bytes=asset.base64?Uint8Array.from(atob(asset.content),c=>c.charCodeAt(0)):asset.content;return new Response(request.method==='HEAD'?null:bytes,{headers:{...security,'Content-Type':asset.type}});}
function json(value,status){return new Response(JSON.stringify(value),{status,headers:{...security,'Content-Type':'application/json; charset=utf-8'}});}
